config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help"      => "static_pages#help"
  get "about"     => "static_pages#about"
  get "contact"   => "static_pages#contact"
  get "signup"    => "users#new"
  get "login"     => "sessions#new"
  post "login"    => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "/users/:id/:type" => "relationships#index"

  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :categories
  resources :words
  resources :lessons
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">

    <div class="alert alert-danger">
      <%= pluralize(object.errors.count, "error") %>.
    </div>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
<% end %>

app/views/shared/_list_lesson.html.erb
<% if @list_lessons.any? %>
  <ol class="lessons">
    <%= render @list_lessons %>
  </ol>
<% end %>

app/views/shared/_request.html.erb
<%= link_to t("word"), "#", class: "btn btn-primary btn-lg" %>
<%= link_to t("lesson"), categories_path, class: "btn btn-primary btn-lg" %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= relationships_path id: @user.id, type: "following" %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t "following" %>
  </a>
  <a href="<%= relationships_path id: @user.id, type: "followers" %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t "followers" %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, Settings.size_picture), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t("view_my_profile"), current_user %></span>