config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help"      => "static_pages#help"
  get "about"     => "static_pages#about"
  get "contact"   => "static_pages#contact"
  get "signup"    => "users#new"
  get "login"     => "sessions#new"
  post "login"    => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "/users/:id/:type" => "relationships#index"

  resources :users
  resources :relationships, only: [:create, :destroy]
  resources :categories
  resources :words
  resources :lessons
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate page: params[:page], per_page: Settings.categories_per_page
  end

  def show
    @category = Category.find params[:id]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params    
    if @category.save
      flash[:success] = I18n.t "category_success"
      redirect_to @category
    else
      render "new"
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update_attributes category_params
      flash[:success] = I18n.t "category_updated"
      redirect_to @category
    else
      render "edit"
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = I18n.t "category_deleted"
    redirect_to categories_url
  end

  private
  def category_params
    params.require(:category).permit :name, :image
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def image_for category, height, width
    image_url = category.image
    image_tag image_url, alt: category.name, height: height, width: width, class: "gravatar img-rounded"
  end
end

app/views/categories/_category.html.erb
<div class="row">
  <part class="col-md-4 col-md-offset-2">
    <%= image_for category, Settings.height_picture_category, Settings.width_picture_category %>
  </part>

  <part class="col-md-4"> 
    <start class="col-md-12">
      <h3><%= link_to category.name, category %></h3> 
    </start>

    <% if current_user.admin? %>
      <start class="col-md-12">    
        <%= link_to t("edit"), edit_category_path(category) %>
        <%= link_to t("delete"), category, method: :delete,
                          data: { confirm: t("confirm") } %>
      </start>
    <% end %>

    <start class="col-md-12">
      <%= t("you_have_learned") %>
    </start>

    <start class="col-md-3 col-md-offset-9">
      <%= link_to t("start"), lessons_path(category_id: category.id), method: :post, class: "btn btn-primary" %>
    </start>
  </part>
</div>

app/views/categories/_create_form.html.erb
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.submit t("create_category"), class: "btn btn-primary" %>
<% end %>

app/views/categories/edit.html.erb
<% provide :title, t("edit_category") %>
<h1><%= t("edit_category") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @category do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :image %>
      <%= f.text_field :image, class: "form-control" %>

      <%= f.submit t("save_changes"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<% provide :title, t("all_categories") %>
<h1><%= t("all_categories") %></h1>

<%= will_paginate %>
  <%= render @categories %>
<%= will_paginate %>

app/views/categories/new.html.erb
<% provide :title, t("category") %>
<h1><%= t("new_category") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "create_form" %>
  </div>
</div>

app/views/categories/show.html.erb
<% provide :title, t("category") %>
<h1><%= t("category") %></h1>
<%= @category.name %>
<%= image_for(@category, 150, 300) %>